name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Login to Github Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push the Docker image
      run: |
        docker build . -t ghcr.io/justinadequate/salesatron5000:latest -t ghcr.io/justinadequate/salesatron5000:$(date +%s)
        docker push ghcr.io/justinadequate/salesatron5000:latest